import { ContractCache } from '@/lib/cache';

const LOTTERY_CACHE_LIST = [
  "lagrange-basis-fp-1024",
  "lagrange-basis-fp-1024.header",
  "lagrange-basis-fp-16384",
  "lagrange-basis-fp-16384.header",
  "lagrange-basis-fp-2048",
  "lagrange-basis-fp-2048.header",
  "lagrange-basis-fp-32768",
  "lagrange-basis-fp-32768.header",
  "lagrange-basis-fp-8192",
  "lagrange-basis-fp-8192.header",
  "lagrange-basis-fq-16384",
  "lagrange-basis-fq-16384.header",
  "srs-fp-65536",
  "srs-fp-65536.header",
  "srs-fq-32768",
  "srs-fq-32768.header",
  // "step-pk-distribution-program-addticket",
  // "step-pk-distribution-program-addticket.header",
  "step-pk-distribution-program-init",
  "step-pk-distribution-program-init.header",
  "step-pk-lottery-buyticket",
  // "step-pk-lottery-buyticket.header",
  // "step-pk-lottery-getcommisionforround",
  // "step-pk-lottery-getcommisionforround.header",
  // "step-pk-lottery-getreward",
  // "step-pk-lottery-getreward.header",
  // "step-pk-lottery-produceresult",
  // "step-pk-lottery-produceresult.header",
  // "step-pk-lottery-refund",
  // "step-pk-lottery-refund.header",
  "step-vk-distribution-program-addticket",
  "step-vk-distribution-program-addticket.header",
  "step-vk-distribution-program-init",
  "step-vk-distribution-program-init.header",
  "step-vk-lottery-buyticket",
  "step-vk-lottery-buyticket.header",
  "step-vk-lottery-getcommisionforround",
  "step-vk-lottery-getcommisionforround.header",
  "step-vk-lottery-getreward",
  "step-vk-lottery-getreward.header",
  "step-vk-lottery-produceresult",
  "step-vk-lottery-produceresult.header",
  "step-vk-lottery-refund",
  "step-vk-lottery-refund.header",
  // "wrap-pk-distribution-program",
  // "wrap-pk-distribution-program.header",
  // "wrap-pk-lottery",
  // "wrap-pk-lottery.header",
  "wrap-vk-distribution-program",
  "wrap-vk-distribution-program.header",
  "wrap-vk-lottery",
  "wrap-vk-lottery.header"
]

export const LOTTERY_CACHE: ContractCache = {
  cachePath: '/dummy_bridge_cache',
  files: LOTTERY_CACHE_LIST,
  urls: LOTTERY_CACHE_LIST.map((x) => `/lottery_cache/${x}`),
};

console.log('Lottery cache', LOTTERY_CACHE);
