export const snakeNames = [
  'znake',
  'cobra',
  'viper',
  'boa',
  'asp',
  'krait',
  'taipan',
  'coral',
  'adder',
  'mamba',
  'racer',
  'garter',
  'keelback',
  'rat snake',
  'tree boa',
  'sea krait',
  'kingsnake',
  'milk snake',
  'corn snake',
  'green snake',
  'brown snake',
  'bush viper',
  'mud snake',
  'water snake',
  'swamp adder',
  'mangrove',
  'vine snake',
  'tentacle',
  'tree viper',
  'night adder',
  'tiger snake',
  'wolf snake',
  'mole snake',
  'tiger keel',
  'sand boa',
  'tree python',
  'sea snake',
  'sand snake',
  'worm snake',
  'egg eater',
  'puff adder',
  'pit viper',
  'boomslang',
  'banded krait',
  'forest cobra',
  'grass snake',
  'mountain',
  'bushmaster',
  'copperhead',
  'cottonmouth',
  'fer-de-lance',
  'horned viper',
  'bush snake',
  'gopher snake',
  'indigo snake',
  'jungle viper',
  'mangrove pit',
  'plains viper',
  'river jack',
  'whip snake',
  'wolf snake',
  'yellowbelly',
  'green racer',
  'habu',
  'hognose',
  'hooknose',
  'kukri',
  'kukri snake',
  'lancehead',
  'ligaya',
  'mountain adder',
  'mud snake',
  'mole viper',
  'puff viper',
  'redbelly',
  'ribbon snake',
  'rock python',
  'rough green',
  'sand viper',
  'saw-scaled',
  'shieldnose',
  'sidewinder',
  'spotted krait',
  'toad snake',
  'twig snake',
  'water cobra',
  'water moccasin',
  'whip snake',
  'worm viper',
  'egg eater',
  'false coral',
  'tree krait',
  'urutu',
  "wagler's pit",
  'white-lipped',
  'yellow pit',
  'zebra spitter',
  'zigzag adder',
];
