export enum GameState {
  WalletNotInstalled,
  WalletNotConnected,
  NotStarted,
  MatchRegistration,
  Matchmaking,
  OpponentTimeout,
  CurrentPlayerHiding,
  WaitingForHiding,
  CurrentPlayerGuessing,
  WaitingForGuessing,
  CurrentPlayerRevealing,
  WaitingForReveal,
  Won,
  Lost,
}
